repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: freeze-requirements
        name: Freeze requirements into requirements.txt
        entry: sh -c 'if command -v uv >/dev/null 2>&1; then uv pip freeze > requirements.txt; else pip freeze > requirements.txt; fi'
        language: system
        always_run: true