# Generated by Django 4.0.1 on 2023-07-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.AutoField(default=0, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
