# Generated by Django 4.0.1 on 2023-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcaster', '0002_alter_podcaster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcaster',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
