# Generated by Django 4.0.1 on 2023-07-26 17:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('podcaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/Podcast')),
                ('insert_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('podcasters', models.ManyToManyField(to='podcaster.Podcaster')),
            ],
        ),
    ]
