# Generated by Django 4.0.1 on 2023-09-05 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCollection',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('insert_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Podcaster',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Podcasters')),
                ('presentation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/Podcast')),
                ('insert_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.podcastcollection')),
                ('podcasters', models.ManyToManyField(to='podcast.Podcaster')),
            ],
        ),
    ]
