# Generated by Django 4.0.1 on 2023-09-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='podcasters',
            field=models.ManyToManyField(blank=True, to='podcast.Podcaster'),
        ),
    ]
