# Generated by Django 4.0.1 on 2024-04-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='MP3_PODCAST/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='podcast_covers/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
