# Generated by Django 4.0.1 on 2024-04-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_alter_podcast_audio_file_alter_podcast_cover_file_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE podcast_podcast ALTER COLUMN insert_time TYPE timestamp with time zone USING timestamp with time zone '1970-01-01' + insert_time::time",
            "ALTER TABLE podcast_podcast ALTER COLUMN insert_time TYPE time USING insert_time::time",
        ),
        migrations.RunSQL(
            "ALTER TABLE podcast_podcast ALTER COLUMN update_time TYPE timestamp with time zone USING timestamp with time zone '1970-01-01' + update_time::time",
            "ALTER TABLE podcast_podcast ALTER COLUMN update_time TYPE time USING update_time::time",
        ),
        migrations.AlterField(
            model_name="podcast",
            name="insert_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
