# Generated by Django 4.0.1 on 2024-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_alter_podcast_insert_time_alter_podcast_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
