# Generated by Django 4.0.1 on 2024-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcast_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcast_audio/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
