# Generated by Django 4.0.1 on 2024-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_alter_podcast_audio_file_alter_podcast_audio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='cover',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='podcast',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='podcast_covers/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='MP3_PODCAST/'),
        ),
    ]
