# Generated by Django 4.0.1 on 2024-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_rename_cover_podcast_cover_url_podcast_cover_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='insert_time',
            field=models.TimeField(null=True),
        ),
    ]
